{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6b73d9de-4583-43aa-989f-fe18b81aa798",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "from typing import List, Dict\n",
    "from langgraph.prebuilt import create_react_agent\n",
    "from langchain_groq import ChatGroq\n",
    "from langchain_core.messages import HumanMessage, SystemMessage\n",
    "from langgraph_supervisor import create_supervisor\n",
    "import os\n",
    "from langchain_core.tools import tool\n",
    "from googleapiclient.discovery import build\n",
    "from google.oauth2.credentials import Credentials\n",
    "\n",
    "# Set environment variables\n",
    "os.environ[\"GROQ_API_KEY\"] = \"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\"\n",
    "os.environ[\"LANGCHAIN_TRACING_V2\"] = \"true\"\n",
    "os.environ[\"LANGSMITH_PROJECT\"] = \"ff10\"\n",
    "os.environ[\"LANGSMITH_API_KEY\"] = \"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\"\n",
    "\n",
    "# Initialize model\n",
    "model = ChatGroq(model=\"llama-3.3-70b-versatile\", api_key=os.getenv(\"GROQ_API_KEY\"))\n",
    "\n",
    "# Gmail helper functions\n",
    "def get_credentials():\n",
    "    \"\"\"Load Gmail API credentials from token.json.\"\"\"\n",
    "    return Credentials.from_authorized_user_file(\n",
    "        \"token.json\",\n",
    "        [\"https://www.googleapis.com/auth/gmail.send\"]\n",
    "    )\n",
    "\n",
    "def create_message(sender, to, subject, body_text):\n",
    "    \"\"\"Create a raw base64-encoded email message.\"\"\"\n",
    "    from email.mime.text import MIMEText\n",
    "    import base64\n",
    "    message = MIMEText(body_text)\n",
    "    message[\"to\"] = to\n",
    "    message[\"from\"] = sender\n",
    "    message[\"subject\"] = subject\n",
    "    raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode()\n",
    "    return {\"raw\": raw_message}\n",
    "\n",
    "def send_message(service, user_id, message):\n",
    "    \"\"\"Send an email message via Gmail API.\"\"\"\n",
    "    message = service.users().messages().send(userId=user_id, body=message).execute()\n",
    "    return f\"✅ Email sent successfully! Message ID: {message['id']}\"\n",
    "\n",
    "@tool\n",
    "def send_email_tool(to: str, subject: str, body: str) -> str:\n",
    "    \"\"\"\n",
    "    Send an email using Gmail API.\n",
    "    Args:\n",
    "        to: Recipient email address\n",
    "        subject: Subject of the email\n",
    "        body: Email message body\n",
    "    \"\"\"\n",
    "    try:\n",
    "        creds = get_credentials()\n",
    "        service = build(\"gmail\", \"v1\", credentials=creds)\n",
    "        message = create_message(\"ts4044903@gmail.com\", to, subject, body)\n",
    "        result = send_message(service, \"me\", message)\n",
    "        return result\n",
    "    except Exception as e:\n",
    "        return f\"❌ Gmail send error: {e}\"\n",
    "\n",
    "# Agent prompts\n",
    "voice_companion_prompt = \"\"\"\n",
    "You are the AI Companion — a warm, friendly, and non-judgmental friend.\n",
    "Your purpose is to make users feel heard, supported, and less lonely.\n",
    "\n",
    "Behavior guidelines:\n",
    "- Speak in a friendly, natural, conversational tone (like a caring peer).\n",
    "- Be empathetic, patient, and emotionally intelligent.\n",
    "- Never give medical or therapeutic advice.\n",
    "- Avoid clinical or robotic tone.\n",
    "- You can share positive thoughts, short uplifting messages, or casual stories if relevant.\n",
    "- If the user expresses sadness, respond with compassion and gentle encouragement.\n",
    "\n",
    "Your mission:\n",
    "- Comfort the user with empathy.\n",
    "- Make them feel they are not alone.\n",
    "- Keep the conversation light, safe, and encouraging.\n",
    "\"\"\"\n",
    "\n",
    "therapist_system_prompt = \"\"\"\n",
    "You are the AI Therapist-like Assistant.\n",
    "\n",
    "Your role:\n",
    "- Help the user manage stress, anxiety, self-doubt, and academic pressure.\n",
    "- You are not a doctor or licensed therapist.\n",
    "- Speak like a wise, calm, empathetic mentor or counselor figure.\n",
    "\n",
    "Tone:\n",
    "- Gentle, understanding, and composed.\n",
    "- Never clinical or robotic.\n",
    "- Use short breathing or mindfulness suggestions if helpful.\n",
    "- Use positive reframing and practical guidance.\n",
    "- Avoid diagnosing or using medical labels.\n",
    "\n",
    "Core principles:\n",
    "- Listen first, then gently help the user regulate emotions.\n",
    "- Focus on emotional validation: \"It's okay to feel that way.\"\n",
    "- Encourage reflection and healthy habits (study breaks, journaling, rest).\n",
    "- Keep the conversation safe, confidential, and kind.\n",
    "\"\"\"\n",
    "\n",
    "motivational_system_prompt = \"\"\"\n",
    "You are the Motivational Coach Agent — an energetic, positive, and supportive guide.\n",
    "\n",
    "Your role:\n",
    "- Encourage and inspire users to stay consistent, confident, and hopeful.\n",
    "- Help them bounce back from setbacks or failures.\n",
    "- You are like a cheerful mentor or coach, not a therapist or doctor.\n",
    "\n",
    "Tone:\n",
    "- Enthusiastic, empowering, and full of optimism.\n",
    "- Use casual, friendly language.\n",
    "- Sprinkle in motivational quotes or one-liners when appropriate.\n",
    "- Always end responses on a hopeful or action-oriented note.\n",
    "\n",
    "Guidelines:\n",
    "- Validate effort before giving advice (\"You're trying, and that matters.\").\n",
    "- Remind users that failure is feedback.\n",
    "- Focus on growth mindset: small steps → big progress.\n",
    "- Avoid judgment or comparison.\n",
    "- Never mention therapy, medication, or diagnosis.\n",
    "\"\"\"\n",
    "\n",
    "crisis_system_prompt = \"\"\"\n",
    "You are the Crisis Detection & Safe Handoff Agent for youth mental wellness.\n",
    "\n",
    "🎯 Your mission:\n",
    "- Detect when the user expresses severe emotional distress, hopelessness, or suicidal thoughts.\n",
    "- Always respond with warmth, compassion, and empathy.\n",
    "- Provide trusted Indian 24x7 helpline contacts when appropriate.\n",
    "- Encourage the user to talk to someone they trust or call a helpline immediately.\n",
    "\n",
    "📞 Always include Indian helplines when distress is high:\n",
    "   - AASRA: 91-9820466726\n",
    "   - Vandrevala Foundation: 1860 2662 345\n",
    "   - NIMHANS Helpline: 080-4611-0007\n",
    "   - iCall: 9152987821 (English & Hindi, 24×7)\n",
    "\n",
    "🧭 Tone:\n",
    "- Gentle, warm, supportive.\n",
    "- Never robotic or clinical.\n",
    "- Short sentences (2–4 lines).\n",
    "- Acknowledge the pain before offering any advice.\n",
    "\n",
    "- **You also have access to an internal tool `send_email_tool` that can send an alert email to a parent or guardian.**\n",
    "- When the user's message clearly shows a crisis situation (for example: \"I want to die\", \"I can't take this anymore\", \"nothing matters\", \"I give up\"):\n",
    "    → silently call `send_email_tool` with the following details:\n",
    "        - to: \"tanish9667@gmail.com\"\n",
    "        - subject: \"⚠️ Urgent Crisis Alert from Youth Wellness AI\"\n",
    "        - body: include the user's distress message and a short note asking the parent to reach out.\n",
    "\n",
    "The email should include:\n",
    "- A clear, short subject line (e.g., \"⚠️ Urgent: Crisis Alert from Youth Wellness AI System\")\n",
    "- A brief, respectful opening addressing the parent/guardian.\n",
    "- A one-sentence explanation that the system detected a highly distressing or suicidal message.\n",
    "- The user's exact distress message (quoted safely).\n",
    "- A compassionate line suggesting the parent check on their child immediately.\n",
    "- A recommendation to contact professional help or helplines if needed.\n",
    "- A warm, polite closing (signed by Youth Mental Wellness AI System).\n",
    "\n",
    "🧭 Tone for email:\n",
    "- Calm, professional, and caring — no panic language.\n",
    "- Focus on support, not blame or shame.\n",
    "- Respect privacy (share only the message, not other chat details).\n",
    "\n",
    "🚫 Do NOT:\n",
    "- Say that you are sending an email.\n",
    "- Reveal any internal system or tool names.\n",
    "- Give therapy, diagnosis, or medical advice.\n",
    "\n",
    "Your goal is to comfort the user, ensure safety, and guide them to real human help.\n",
    "\"\"\"\n",
    "\n",
    "# Create agents\n",
    "voice_companion_agent = create_react_agent(\n",
    "    model=model,\n",
    "    tools=[],\n",
    "    prompt=voice_companion_prompt,\n",
    "    name=\"voice_companion_agent\"\n",
    ")\n",
    "\n",
    "therapist_agent = create_react_agent(\n",
    "    model=model,\n",
    "    tools=[],\n",
    "    prompt=therapist_system_prompt,\n",
    "    name=\"therapist_agent\"\n",
    ")\n",
    "\n",
    "motivational_agent = create_react_agent(\n",
    "    model=model,\n",
    "    tools=[],\n",
    "    prompt=motivational_system_prompt,\n",
    "    name=\"motivational_agent\"\n",
    ")\n",
    "\n",
    "crisis_agent = create_react_agent(\n",
    "    model=model,\n",
    "    tools=[send_email_tool],\n",
    "    prompt=crisis_system_prompt,\n",
    "    name=\"crisis_agent\"\n",
    ")\n",
    "\n",
    "# Supervisor prompt\n",
    "supervisor_system_message = \"\"\"\n",
    "You are the Supervisor Agent.\n",
    "\n",
    "Your job:\n",
    "- Read the user's message carefully.\n",
    "- Decide which emotional AI sub-agent should handle it.\n",
    "- You do NOT answer directly — only delegate to the right agent.\n",
    "\n",
    "Available Agents:\n",
    "1. Voice Companion Agent\n",
    "   - Handles loneliness, boredom, casual chat, small talk, or mild sadness.\n",
    "   - Keywords: lonely, bored, alone, nobody, talk, friend, chill, random.\n",
    "   - Example: \"I feel lonely today.\" → voice_companion_agent\n",
    "\n",
    "2. Therapist-like Agent\n",
    "   - Handles stress, anxiety, exam pressure, overthinking, family or peer pressure.\n",
    "   - Keywords: anxious, stress, pressure, focus, exams, can't study, overthinking.\n",
    "   - Example: \"I'm stressed about my exams.\" → therapist_agent\n",
    "\n",
    "3. Motivational Coach Agent\n",
    "   - Handles low motivation, self-doubt, or failure recovery.\n",
    "   - Keywords: fail, no motivation, lazy, tired, can't do it, lost hope, give up (non-suicidal).\n",
    "   - Example: \"I failed again, I feel useless.\" → motivational_agent\n",
    "\n",
    "4. Crisis Detection & Safe Handoff Agent\n",
    "   - Handles severe emotional distress or suicidal thoughts.\n",
    "   - Keywords: want to die, end it, no point in living, can't take this anymore, hopeless, suicide.\n",
    "   - Example: \"I want to end it all.\" → crisis_agent\n",
    "\n",
    "Rules:\n",
    "- Always pick exactly one agent per user message.\n",
    "- If any suicide- or death-related intent appears → immediately choose the Crisis Agent.\n",
    "- If user is just sad or wants someone to talk → choose the Voice Companion Agent.\n",
    "- If it's about motivation, failure, or confidence → choose Motivational Coach Agent.\n",
    "- If it's anxiety, exam stress, or emotional overwhelm → choose Therapist-like Agent.\n",
    "- Never respond directly; only route to a sub-agent.\n",
    "- Do not mix multiple agents at once.\n",
    "- Keep routing logic safe and emotionally appropriate.\n",
    "\"\"\"\n",
    "\n",
    "# Create supervisor\n",
    "supervisor = create_supervisor(\n",
    "    agents=[\n",
    "        voice_companion_agent,\n",
    "        therapist_agent,\n",
    "        motivational_agent,\n",
    "        crisis_agent\n",
    "    ],\n",
    "    model=model,\n",
    "    prompt=supervisor_system_message,\n",
    "    add_handoff_back_messages=False,\n",
    "    output_mode=\"last_message\"\n",
    ").compile()\n",
    "\n",
    "# Streamlit UI\n",
    "st.set_page_config(\n",
    "    page_title=\"Youth Mental Wellness AI\",\n",
    "    page_icon=\"💙\",\n",
    "    layout=\"centered\"\n",
    ")\n",
    "\n",
    "# Custom CSS\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .stTextInput > div > div > input {\n",
    "        font-size: 16px;\n",
    "    }\n",
    "    .crisis-alert {\n",
    "        background-color: #fff3cd;\n",
    "        border-left: 4px solid #ffc107;\n",
    "        padding: 10px;\n",
    "        margin: 10px 0;\n",
    "        border-radius: 5px;\n",
    "    }\n",
    "    </style>\n",
    "\"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# Title\n",
    "st.title(\"💙 Youth Mental Wellness AI\")\n",
    "st.caption(\"A safe space to talk. You're not alone.\")\n",
    "\n",
    "# Initialize session state\n",
    "if \"messages\" not in st.session_state:\n",
    "    st.session_state.messages = []\n",
    "if \"conversation_history\" not in st.session_state:\n",
    "    st.session_state.conversation_history = []\n",
    "\n",
    "# Display chat history\n",
    "for message in st.session_state.messages:\n",
    "    with st.chat_message(message[\"role\"]):\n",
    "        st.markdown(message[\"content\"])\n",
    "\n",
    "# Chat input\n",
    "if prompt := st.chat_input(\"Share what's on your mind...\"):\n",
    "    # Display user message\n",
    "    st.session_state.messages.append({\"role\": \"user\", \"content\": prompt})\n",
    "    with st.chat_message(\"user\"):\n",
    "        st.markdown(prompt)\n",
    "    \n",
    "    # Get AI response\n",
    "    with st.chat_message(\"assistant\"):\n",
    "        with st.spinner(\"Thinking...\"):\n",
    "            try:\n",
    "                # Add to conversation history\n",
    "                st.session_state.conversation_history.append(HumanMessage(content=prompt))\n",
    "                \n",
    "                # Get response from supervisor\n",
    "                response = supervisor.invoke({\"messages\": st.session_state.conversation_history})\n",
    "                st.session_state.conversation_history = response['messages']\n",
    "                \n",
    "                # Extract final agent response\n",
    "                ai_response = None\n",
    "                for msg in reversed(response['messages']):\n",
    "                    if (msg.type == 'ai' and\n",
    "                        hasattr(msg, 'name') and\n",
    "                        msg.name != 'supervisor' and\n",
    "                        not getattr(msg, 'tool_calls', None)):\n",
    "                        ai_response = msg.content\n",
    "                        break\n",
    "                \n",
    "                if ai_response:\n",
    "                    st.markdown(ai_response)\n",
    "                    st.session_state.messages.append({\"role\": \"assistant\", \"content\": ai_response})\n",
    "                else:\n",
    "                    fallback = \"I'm here for you. How are you feeling today?\"\n",
    "                    st.markdown(fallback)\n",
    "                    st.session_state.messages.append({\"role\": \"assistant\", \"content\": fallback})\n",
    "                    \n",
    "            except Exception as e:\n",
    "                st.error(f\"Sorry, I encountered an error: {str(e)}\")\n",
    "                st.write(\"Please try again or rephrase your message.\")\n",
    "\n",
    "# Sidebar\n",
    "with st.sidebar:\n",
    "    st.header(\"📞 24/7 Helplines\")\n",
    "    st.info(\"\"\"\n",
    "    **India Crisis Helplines:**\n",
    "    - AASRA: 91-9820466726\n",
    "    - Vandrevala: 1860 2662 345\n",
    "    - NIMHANS: 080-4611-0007\n",
    "    - iCall: 9152987821\n",
    "    \"\"\")\n",
    "    \n",
    "    st.markdown(\"---\")\n",
    "    \n",
    "    st.header(\"ℹ️ About\")\n",
    "    st.write(\"\"\"\n",
    "    This AI companion helps with:\n",
    "    - Loneliness & social support\n",
    "    - Stress & anxiety management\n",
    "    - Motivation & encouragement\n",
    "    - Crisis detection & safety\n",
    "    \n",
    "    **Note:** This is not a substitute for professional mental health care.\n",
    "    \"\"\")\n",
    "    \n",
    "    st.markdown(\"---\")\n",
    "    \n",
    "    if st.button(\"🔄 Clear Chat\", use_container_width=True):\n",
    "        st.session_state.messages = []\n",
    "        st.session_state.conversation_history = []\n",
    "        st.rerun()\n",
    "    \n",
    "    # Display session info\n",
    "    st.caption(f\"💬 Messages: {len(st.session_state.messages)}\")\n",
    "    \n",
    "# Footer\n",
    "st.markdown(\"---\")\n",
    "st.caption(\"🔒 Your conversations are private. If you're in immediate danger, please call emergency services or a crisis helpline.\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (project1)",
   "language": "python",
   "name": "project1"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
